MvcStorageFileAzure/Models/Equipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcStorageFileAzure.Models
{
    public class Equipo
    {
        public String Nombre { get; set; }
        public String Imagen { get; set; }
    }
}

MvcStorageFileAzure/Models/Motorista.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcStorageFileAzure.Models
{
    public class Motorista
    {
        public String Nombre { get; set; }
        public String Dorsal { get; set; }
        public String Titulos { get; set; }
        public String Debut { get; set; }
        public List<Equipo> Equipo { get; set; }
    }
}

MvcStorageFileAzure/Controllers/StorageFileController.cs
using MvcStorageFileAzure.Models;
using MvcStorageFileAzure.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcStorageFileAzure.Controllers
{
    public class StorageFileController : Controller
    {
        RepositoryStorageFile repo;
        public StorageFileController()
        {
            this.repo = new RepositoryStorageFile();
        }
        // GET: Index
        public ActionResult Index()
        {
            List<String> files = this.repo.GetStorageFiles();
            return View(files);
        }
        // GET: UploadFile
        public ActionResult UploadFile()
        {
            return View();
        }
        // POST: UploadFile
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            Stream stream = file.InputStream;
            repo.UploadFile(file.FileName, stream);
            ViewBag.Mensaje = "El fichero seleccionado se ha subido a Azure correctamente.";
            return View();
        }
        //GET: DeleteFile
        public ActionResult DeleteFile(String filename)
        {
            this.repo.DeleteFile(filename);
            return RedirectToAction("Index");
        }
        //GET: ReadTxtFile
        public ActionResult ReadTxtFile(String filename)
        {
            String filecontent = this.repo.ReadTxt(filename);
            ViewBag.Contenido = filecontent;
            return View();
        }
        //GET: ReadXmlFile
        public ActionResult ReadXmlFile(String filename)
        {
            List<Motorista> motoristas = this.repo.ReadXmlFile(filename);
            return View(motoristas);
        }
    }
}

MvcStorageFileAzure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MvcStorageFileAzure/Views/StorageFile/Index.cshtml
@model List<String>
@{
    ViewBag.Title = "Index";
}

<h2>Ficheros encontrados en Azure Storage</h2>

<h3>@Html.ActionLink("Subir Archivo", "UploadFile", "StorageFile")</h3>

@if (Model != null)
{
    <table class="table table-bordered">
        <tr>
            <td>Nombre</td>
            <td>Opciones</td>
        </tr>
        @foreach (String file in Model)
        {
            <tr>
                <td>@file</td>
                <td>
                    @if (file.EndsWith("xml"))
                    {
                        @Html.ActionLink("Ver archivo", "ReadXmlFile", "StorageFile", new { filename = file }, null)
                    }
                    else if (file.EndsWith("txt"))
                    {
                        @Html.ActionLink("Ver archivo", "ReadTxtFile", "StorageFile", new { filename = file }, null)
                    } |
                    @Html.ActionLink("Eliminar archivo", "DeleteFile", "StorageFile", new { filename = file }, null)
                </td>
            </tr>
        }
    </table>
}

MvcStorageFileAzure/Views/StorageFile/ReadTxtFile.cshtml
@{
    ViewBag.Title = "_ReadTxtFile";
}
<h2>Contenido del fichero TXT</h2>
@if (ViewBag.Contenido != null)
{
    <h4>@ViewBag.Contenido</h4>
}
else
{
    <h4 style=”color:red”>Error</h4>
}
<br />

@Html.ActionLink("Volver al listado", "Index", "StorageFile")

MvcStorageFileAzure/Views/StorageFile/ReadXmlFile.cshtml
@model IEnumerable<MvcStorageFileAzure.Models.Motorista>

@{
    ViewBag.Title = "ReadXmlFile";
}

<h2>ReadXmlFile</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dorsal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Debut)
        </th>
        <th>@Html.DisplayNameFor(model => model.Equipo)</th>
        <th>Imagen del equipo</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Dorsal" style="width:110px;height:100px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Debut)
            </td>
            @foreach (var eq in item.Equipo)
            {
                <td>
                    <p>@eq.Nombre</p>
                </td>
                <td>
                    <span><img src="@eq.Imagen" style="width:150px;height:100px;" /></span>
                </td>
            }
        </tr>
    }
</table>

@Html.ActionLink("Volver al listado", "Index", "StorageFile")

MvcStorageFileAzure/Views/StorageFile/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>Subir archivo a Azure Storage File</h2>

<form method="post" enctype="multipart/form-data">
    <div>
        <label>Seleccione un archivo:</label>
        <input type="file" name="file" size="25" class="form-control" />    
    </div>
    <br />
    <div>
        <button type="submit" class="btn btn-success">Subir fichero</button>
    </div>
</form>

<h3 style="color:green">
    @ViewBag.Mensaje
</h3>

@Html.ActionLink("Volver", "Index", "StorageFile")